# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build solution
      run: dotnet build --no-restore
    - name: Start MongoDB server
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: latest
        mongodb-port: 27017
        #mongodb-username: testuser
        #mongodb-password: TestPa5s!k
        mongodb-db: ugtest
    - name: Wait / Sleep
      uses: jakejarvis/wait-action@v0.1.1
      with:
        time: 5s
    - name: Create Mongodb user
      run: mongo admin --eval "db.createUser({user:'testuser',pwd:'TestPa5s!k',roles:[{role:'readwrite',db:'ugtest'}]})"
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
