# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: MongoDB for GitHub Actions
    # You may pin to the exact commit or the version.
      uses: timgchile/mongodb-github-action@1.7.4
      with:
        # MongoDB version to use (default "latest")
        mongodb-version: latest
        mongodb-port: 27017
        mongodb-username: testuser
        mongodb-password: TestPa5s!k
        mongodb-db: ugtest
    - name: Test
      run: dotnet test --no-build --verbosity normal
